services:
  ledger-api:
    build:
      context: ./Carrefour.API.Ledger
      dockerfile: Dockerfile
    container_name: ledger-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__dbHost=postgres
    depends_on:
      postgres:
        condition: service_healthy

  business-intelligence-api:
    build:
      context: ./Carrefour.API.BusinessIntelligence
      dockerfile: Dockerfile
    container_name: business-intelligence-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__dbHost=postgres
      - ConnectionStrings__redisHost=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  business-intelligence-etl:
    build:
      context: ./Carrefour.ETL.BusinessIntelligence
      dockerfile: Dockerfile
    container_name: business-intelligence-etl
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__dbHost=postgres
    depends_on:
      postgres:
        condition: service_healthy
      ledger-api:
        condition: service_started
      business-intelligence-api:
        condition: service_started

  postgres:
    image: postgres:18-alpine
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7jur60
      POSTGRES_DB: db_carrefour
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_carrefour"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass 7jur60 --save 60 1
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
    driver: local