FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Carrefour.API.Ledger.csproj", "./"]
RUN dotnet restore

COPY . .
RUN dotnet publish "Carrefour.API.Ledger.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app


EXPOSE 8080
EXPOSE 8081

USER app

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Carrefour.API.Ledger.dll"]