FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Carrefour.ETL.BusinessIntelligence.csproj", "./"]
RUN dotnet restore

COPY . .
RUN dotnet publish "Carrefour.ETL.BusinessIntelligence.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

USER app

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Carrefour.ETL.BusinessIntelligence.dll"]