// <auto-generated />
using System;
using Carrefour.API.Ledger.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carrefour.API.Ledger.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260819172649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carrefour.API.Ledger.Models.LedgerActivity", b =>
                {
                    b.Property<long>("idLedgerActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ledger_activity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idLedgerActivity"));

                    b.Property<DateTime>("dateTimeInclusion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_inclusion");

                    b.Property<int>("operation")
                        .HasColumnType("integer")
                        .HasColumnName("operation");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("idLedgerActivity");

                    b.ToTable("ledger_activity");
                });
#pragma warning restore 612, 618
        }
    }
}
