// <auto-generated />
using System;
using Carrefour.API.BusinessIntelligence.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carrefour.API.BusinessIntelligence.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carrefour.API.BusinessIntelligence.Models.DailyConsolidated", b =>
                {
                    b.Property<long>("idDailyConsolidated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_daily_consolidated");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idDailyConsolidated"));

                    b.Property<DateOnly>("consolidatedDate")
                        .HasColumnType("date")
                        .HasColumnName("consolidated_date");

                    b.Property<int>("creditQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("credit_quantity");

                    b.Property<int>("debitQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("debit_quantity");

                    b.Property<long>("idLastLedgerActivity")
                        .HasColumnType("bigint")
                        .HasColumnName("id_last_ledger_activity");

                    b.Property<decimal>("valueCredit")
                        .HasColumnType("numeric")
                        .HasColumnName("value_credit");

                    b.Property<decimal>("valueDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("value_debit");

                    b.HasKey("idDailyConsolidated");

                    b.ToTable("daily_consolidated");
                });
#pragma warning restore 612, 618
        }
    }
}
